import type { FetchResult } from "../fetchers/index.js";

export function renderMarkdown(data: FetchResult): string {
  const lines: string[] = [];

  lines.push("# Version Reference");
  lines.push("");
  lines.push("> Auto-generated by [versionlens](https://github.com/utlty/versionlens)");
  lines.push(`> Last updated: ${data.timestamp}`);
  lines.push(">");
  lines.push("> **AI agents: read this file before suggesting any package versions,");
  lines.push("> runtime versions, or AI model IDs. Do NOT hallucinate version numbers.**");
  lines.push("");

  // Runtimes
  if (data.runtimes.length) {
    lines.push("## Runtimes");
    lines.push("");
    lines.push("| Runtime | Latest Stable |");
    lines.push("|---------|---------------|");
    for (const rt of data.runtimes) {
      lines.push(`| ${rt.name} | ${rt.version} |`);
    }
    lines.push("");
  }

  // npm
  if (data.npm.length) {
    lines.push("## npm Packages");
    lines.push("");
    lines.push("| Package | Latest |");
    lines.push("|---------|--------|");
    for (const pkg of data.npm) {
      lines.push(`| ${pkg.name} | ${pkg.version} |`);
    }
    lines.push("");
  }

  // pip
  if (data.pip.length) {
    lines.push("## pip Packages");
    lines.push("");
    lines.push("| Package | Latest |");
    lines.push("|---------|--------|");
    for (const pkg of data.pip) {
      lines.push(`| ${pkg.name} | ${pkg.version} |`);
    }
    lines.push("");
  }

  // Docker
  if (data.docker.length) {
    lines.push("## Docker Images");
    lines.push("");
    lines.push("| Image | Latest Stable Tag | Digest |");
    lines.push("|-------|-------------------|--------|");
    for (const img of data.docker) {
      const digest = img.digest ? img.digest : "-";
      lines.push(`| ${img.name} | ${img.tag} | ${digest} |`);
    }
    lines.push("");
  }

  // GitHub releases
  if (data.github.length) {
    lines.push("## GitHub Releases");
    lines.push("");
    lines.push("| Repository | Latest |");
    lines.push("|------------|--------|");
    for (const repo of data.github) {
      lines.push(`| ${repo.name} | ${repo.version} |`);
    }
    lines.push("");
  }

  // AI Models
  if (data.ai_models.length) {
    lines.push("## AI Models");
    lines.push("");
    for (const provider of data.ai_models) {
      lines.push(`### ${provider.provider}`);
      for (const model of provider.models) {
        lines.push(`- ${model}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [versionlens](https://github.com/utlty/versionlens)*");
  lines.push("");

  return lines.join("\n");
}
